plugins:
  opa:
    policy-templates: ./policy-templates/develop/opa
    policy-output: ./policies/opa
    policy-results: ./policy-results/opa
    bundle: bundle.tar.gz
    bundle-revision: {{ RUNID }}